<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    //
    protected $fillable =  [
        'title', 'path', 'parent'
    ];
    public function delete($options = [])
    {
        self::where('parent', $this->id)->delete();

        return parent::delete(); // Change the autogenerated stub
    }
}
